# Generated by Django 2.0.2 on 2018-08-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millionaire', '0002_auto_20180813_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer_text',
            field=models.CharField(default='Computer', max_length=200),
            preserve_default=False,
        ),
    ]
