# Generated by Django 2.1 on 2018-08-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('millionaire', '0004_auto_20180813_1528'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='userscore',
        #     old_name='best_score',
        #     new_name='score',
        # ),
    ]
